### PR TITLE
harvester plugin

### PR DESCRIPTION
**Pull request by WuJun2016**
### Summary
Hi @richard-cox  This is about the functionality related to the harvester plugin that we discussed before.   Can you help review to see what's wrong ?  thanks

1. The harvester-plugin built into the rancher is placed in the following location
image

2. CI-related features are not yet complete, where does rancher want to put the packaged harvester plugin ? 

3. For this [PR](https://github.com/richard-cox/dashboard/pull/9/files#diff-fb0893fe4b53f518d4bf7bc279ca656f52a2df4f14a2a95fe836a0af16bb2a79R77) , I have a question as to whether we should save the harvester-plugin version built into Rancher in Rancher's configuration ?     

Fixes #

### CODE REVIEW

**Comment by WuJun2016** [comment]
1. ui-plugin-index:  `https://releases.rancher.com/harvester-ui/dashboard/plugin/harvester-11.1.0.umd.min.js`

**Comment by richard-cox** [comment]
@WuJun2016 There will probably be some big changes to this branch when updated with https://github.com/rancher/dashboard/pull/6729. 

1) That looks about correct. There's a `v3/settings` `ui-dashboard-path` value that determines it. On my setting this is `/usr/share/rancher/ui-dashboard`
2) Not quite sure i understand the question. For the built-in use case the dashboard build process will fetch the harvester package from a url provided by yourselves (or we can add it directly to the rancher/dashboard repo). For the use case where the harvester package is served up by the harvester cluster that's something for the harvester team to determine (but loaded via the dashboard as per this PR `pkgUrl = `k8s/clusters/${ clusterId }/v1/harvester/plugin-assets/${ fileName }`;`
3) As the version of the built-in harvester plugin will never change, we can have it hardcoded. 

> 1. ui-plugin-index:  `https://releases.rancher.com/harvester-ui/dashboard/plugin/harvester-11.1.0.umd.min.js`
> 2. harvester image: `futuretea/harvester:expose-setting-head`

Does the ui-plugin-index relate to question 2?

Can i use that image when installing rancher via https://docs.harvesterhci.io/v1.0/dev/dev-mode/?
```
--set rancherImage=futuretea/harvester \
--set rancherImageTag=expose-setting-head \
```

On a side note, I ran through the install today from that page and got the following error

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "prometheus-longhorn-rules" namespace: "longhorn-system" from "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "longhorn-prometheus-servicemonitor" namespace: "longhorn-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
```

After installing monitoring first harvester successfully installed... however I cannot reach the dashboard (initial request errors with a 503 and the tab shows a `Handler disconnected` error

**Comment by w13915984028** [comment]
@richard-cox 

Could you help try add below condition to the relad yaml and try again, thanks.

```
{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule" -}}

// deploy/charts/harvester/templates/longhorn-prometheusrule.yaml

{{- end }}



{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" -}}
// deploy/charts/harvester/templates/longhorn-service-monitor.yaml
{{- end }}
```

**Comment by WuJun2016** [comment]
@richard-cox  I understand that when nacny's harvester-plugin pr is merged, a lot of the code will be different from your code in this branch, but I think the main logic about jumping should be fine with your code in this pr.

2.  For the version of the harvester plugin embedded in the rancher:   
    1. During the development phase, the rancher ui should be going to this address `https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3-head.tar.gz` to get the plugin 
    2. In the Release phase, the rancher ui should be going to this address `https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3.tar.gz` to get the plugin.
    
3. As the product iterates, the version of the harvester-plugin embedded in `rancher 2.7` may be `v1.0.3-p1`, and the version embedded in `rancher 2.8` may be `v1.0.3-p2`，   
  So I don't think this [value](https://github.com/richard-cox/dashboard/pull/9/files#diff-fb0893fe4b53f518d4bf7bc279ca656f52a2df4f14a2a95fe836a0af16bb2a79R77) should be a fixed variable，  I think this value should be a good choice to save in the backend ？


4. `ui-plugin-index` ： This value is for harvester v1.1.0 ui to configure the plugin address.    

5. Can you access the fremont environment? The harvester-ui team uses an online environment to start a new harvester via harvester-in-harvester.
 but the fremont environment is being reinstalled right now, if you have access, I'll send you the address later.

**Comment by richard-cox** [comment]
2. I think there's a few use cases to cover
   - Developer running the dashboard making changes to the pkg to fix bugs/add features. This can be done either by
     1) Running the harvester pkg inline with the dashboard. (I need to make sure the dynamic loader works this way)
     2) Build the harvester pkg locally, serve it locally and ensure it's loaded via url. (this needs validating too)
   - Non-developer wants to run the latest dashboard and harvester pkg inbetween the release cycles
     The dashboard will load whatever version is supplied by `ui-plugin-index`, i'm not sure where that value comes from but it could determine the url given the version (`-head`) and provide the appropriate url. 
   - Users of a released product
     This will use the `ui-plugin-index` (if available) as well
3. Ok, i see, so the embedded harvester plugin is still liable to change. The plugin will only ever get updated when Rancher Manager ships though (as it's embedded in it), so it's not something that would happen at run time and needs a backend setting. To make this process easier we could put the harvester plugin version (`1.0.3-p1`, `1.0.3-p2`, etc) into a build time setting. That could then be used in the Rancher build process (to fetch the version that will be bundled with it) and in the code that loads it?
5. I don't think so, that's separate to the SUSE engineering cloud? I managed to get harvester running locally again by going back before the commit that brought in monitoring. It's weird, as i tried installing monitoring before harvester and that failed too. Either way, will give a try with @w13915984028's suggestion (thanks!)
6. Sorry, think this one got lost, there was a reference to a harvester image `futuretea/harvester:expose-setting-head`. Can that be applied via the process over at https://docs.harvesterhci.io/v1.0/dev/dev-mode/?
   ```
   --set rancherImage=futuretea/harvester \
   --set rancherImageTag=expose-setting-head \
   ````

On a side note - I've now updated this branch with the latest harvester changes (which have been merged to master - that should all work when the harvester plugin is built alongside the dashboard). There's some fixes in this PR for when the harvester plugin is built and loaded outside of hte dashboard. I've also created a [PR](https://github.com/rancher/dashboard/pull/6794) with some info

**Comment by WuJun2016** [comment]
2. > Non-developer wants to run the latest dashboard and harvester pkg inbetween the release cycles
The dashboard will load whatever version is supplied by ui-plugin-index, i'm not sure where that value comes from but it could determine the url given the version (-head) and provide the appropriate url.
-  If the user imports a cluster with the latest version of harvester （Support plugins),  during the development phase, when built master branch iso, the latest (https://releases.rancher.com/harvester-ui/plugin/harvester-latest.tar.gz) harvester pkg is built in (we can get it via v1/harvester /plugin-assets).
- If the user is imports an old harvester （v1.0.2,   v1.0.3）,    This is a problem, the harvester pkg that the user can get is always the version that was packaged in when the user installed rancher.  So I wonder if the setting of the rancher can also add a configuration to set the address of the plugin ?   when the value of `ui-offline-preferred `is equal to `remote`, we will get the latest plugin address from the setting of the rancher.  
  In the development phase, I think the setting value should be like this: `https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3-head/harvester-1.0.3-head.umd.min.js`
  At release time, the setting should be: https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3/harvester-1.0.3.umd.min.js

> Users of a released product
> This will use the ui-plugin-index (if available) as well
Yes, whether it is a master-head version or a released version, if it is a harvester that supports plugin, the user can determine the pull address of the harvester pkg by configuring ui-plugin-index.

But for harvester that doesn't support plugin, as I said above we need to add a configuration in the setting of the rancher.



3.
>  To make this process easier we could put the harvester plugin version (1.0.3-p1, 1.0.3-p2, etc) into a build time setting. That could then be used in the Rancher build process (to fetch the version that will be bundled with it) and in the code that loads it?

I don't understand what this means.    Do you mean to write this version information in the code of rancher dashborad? then change it every release ?

4.   I haven't tried running it locally.  @guangbochen   Can you provide an online environment for the rancher team colleagues to use? I think it would be much easier


5.   `futuretea/harvester:expose-setting-head`   is a harvester image, it cannot be used like this, it is better to use the v1.0.3 iso to install an harvester.

**Comment by WuJun2016** [comment]
@richard-cox  I have two small questions:  
1.   Do you want the build harvester plugin to be executed in the rancher repo or in the harvester repo ？ 
https://github.com/harvester/dashboard/blob/release-harvester-plugin-v1.0/.drone.yml#L340  
https://github.com/harvester/dashboard/blob/release-harvester-plugin-v1.0/shell/scripts/build-pkg.sh#L73

If you want to do it in the rancher repo, I will push the CI pr changes to the rancher.    

2.  When will your branch plan merge into the Master ？
https://github.com/richard-cox/dashboard/tree/test-pluginize-rc-2

**Comment by richard-cox** [comment]
I like the idea of bringing in `ui-offline-prefered`.

For the developer use case where they are changing code and testing it, i think the below is still valid for both the built-in and the latest and greatest cases
- Running the harvester pkg inline with the dashboard. (I need to make sure the dynamic loader works this way)
- Build the harvester pkg locally, serve it locally and ensure it's loaded via url. (this needs validating too)

Once that code has been pushed to a repo somewhere and a build of the pkg's has been created then the use cases differ.

The cluster fails to return `/v1/harvester/uiinfo` (harvester cluster is old and doesn't contain the harvester plugin)
- `ui-offline-preferred` === Local. The harvester plugin that's packaged with the dashboard is used
- `ui-offline-preferred` === Remote. The harvester plugin from https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3-head/harvester-1.0.3-head.umd.min.js is used
- `ui-offline-preferred` === Dynamic. If the version ends in `-head` the result is as is `Remote`, otherwise `Local`

> Note - When the fall back package is updated in the dashboard (going from 1.0.3-p1 --> 1.0.3-p2) `Remote` url will also be updated


That leaves the case where the harvester cluster has a packaged plugin
The cluster returns `/v1/harvester/uiinfo`
- `ui-offline-preferred` === Local. The harvester plugin that's in `ui-plugin-index` served up by the cluster is used, for instance `/v1/harvester/plugin-assets/harvester-1.3.3.umd.min.js`
- `ui-offline-preferred` === Remote. The harvester plugin from releases.rancher.com is used. The version comes from ui-plugin-index and is suffixed with -`head`, for instance `https://releases.rancher.com/harvester-ui/plugin/harvester-1.3.3-head/harvester-1.3.3-head.umd.min.js`
- `ui-offline-preferred` === Dynamic. If the version ends in `-head` the result is as is `Remote`, otherwise `Local`


This should allow people to test / use changes to either built-in plugin or latest plugin before a release. It also works in a similar way to the dashboard (with the ui-offline-prefered).

Alternatives from your comment
- When the cluster returns `/v1/harvester/uiinfo` the dashboard ignores `ui-offline-preferred` and always uses `ui-plugin-index`. The harvester team will ensure pre-release this points to the `-head` version of the package, and for release the released harvester plugin.
- When `ui-offline-preferred` === Remote the url to go to comes from a harvester setting. One for each of the two scenarios above. The harvester team ensures these settings reference a suitable `-head` build

>     1. Do you want the build harvester plugin to be executed in the rancher repo or in the harvester repo ？
>        https://github.com/harvester/dashboard/blob/release-harvester-plugin-v1.0/.drone.yml#L340
>        https://github.com/harvester/dashboard/blob/release-harvester-plugin-v1.0/shell/scripts/build-pkg.sh#L73

As long as the plugins are built within a fork of the dashboard repo I think the build could happen anywhere. If they happen in the harvester dashboard repo then all future changes should go directly there and the harvester plugin removed from the dashboard repo. It might make sense to do that after most of the dev work is done though. Any preferences your side? 

> It seems to have been merged in, I'm pushing my pr directly to master ？

The PR that does the initial move of harvester plugin assets has merged. I've now merged that in to my branch and created a PR to get it into rancher/dashboard (https://github.com/rancher/dashboard/pull/6794). This branch contains some fixes and improvements over the first PR.

**Comment by WuJun2016** [comment]
> The cluster fails to return /v1/harvester/uiinfo (harvester cluster is old and doesn't contain the harvester plugin)
> ui-offline-preferred === Remote. The harvester plugin from https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3-head/harvester-1.0.3-head.umd.min.js is used

In this case, the frontend hardcodes the address into the code and doesn't need to go through the setting value to get it, right ?    (If Yes, then I have no problem and I continue to follow this method to improve the code),    But if hard-coded, it's not very flexible, there's no way to replace the address, for example, if the user or developer builds the address themselves and wants to replace it.


> That leaves the case where the harvester cluster has a packaged plugin
This case, the current solution I discussed with @guangbochen is to use the ui-source inside the harvester setting, not the ui-offline-preferred inside the rancher.     

image

> As long as the plugins are built within a fork of the dashboard repo I think the build could happen anywhere. If they happen in the harvester dashboard repo then all future changes should go directly there and the harvester plugin removed from the dashboard repo. It might make sense to do that after most of the dev work is done though. Any preferences your side?

let's build the plugin in the rancher repo,   I think this is more secure. After the plugin function is stable, after the harvester is removed in the rancher in the future version, we can change it build in the harvester.

I will push the CI related pr to the rancher later.

**Comment by richard-cox** [comment]
Think we've got there!

> In this case, the frontend hardcodes the address into the code and doesn't need to go through the setting value to get it, right ? (If Yes, then I have no problem and I continue to follow this method to improve the code), But if hard-coded, it's not very flexible, there's no way to replace the address, for example, if the user or developer builds the address themselves and wants to replace it.

Correct, it wouldn't come from settings. If you'd like more flexiblity though there could be an override from settings, something like `ui-dashboard-harvester-remote-plugin`?

> That leaves the case where the harvester cluster has a packaged plugin
> This case, the current solution I discussed with @guangbochen is to use the ui-source inside the harvester setting, not the ui-offline-preferred inside the rancher.

Ok, `ui-offline-prefered` won't be used.

---- 
So the updated process is...


For the developer use case where they are changing code and testing it, i think the below is still valid for both the built-in and the latest and greatest cases
- Running the harvester pkg inline with the dashboard. (I need to make sure the dynamic loader works this way)
- Build the harvester pkg locally, serve it locally and ensure it's loaded via url. (this needs validating too)

Once that code has been pushed to `rancher/dashboard` and a build of the pkg's has been created then the use cases differ.

The cluster fails to return `/v1/harvester/uiinfo` (harvester cluster is old and doesn't contain the harvester plugin)
- `ui-offline-preferred` === Local. The harvester plugin that's packaged with the dashboard is used
- `ui-offline-preferred` === Remote. The harvester plugin from a new settings `ui-dashboard-harvester-remote-plugin` is used (to be provided by the harvester team, default empty). If the setting is empty we fall back on `https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3-head/harvester-1.0.3-head.umd.min.js`.
- `ui-offline-preferred` === Dynamic. If the version ends in `-head` the result is as is `Remote`, otherwise `Local`

That leaves the case where the harvester cluster has a packaged plugin
The cluster returns `/v1/harvester/uiinfo`
- Regardless of `ui-offline-prefered` the harvester plugin that's provided by `ui-plugin-index` will be used, for example `/v1/harvester/plugin-assets/harvester-1.3.3.umd.min.js`. Normally this is the one provided by the cluster in question

-----
> let's build the plugin in the rancher repo, I think this is more secure. After the plugin function is stable, after the harvester is removed in the rancher in the future version, we can change it build in the harvester.

Understood.

As a summary of steps and owners

Dashboard Team
- Bundle a version of the harvester plugin with the dashboard (a built pkg located and served from the `/dashboard` root)
- Merge remaining Dashboard [PR](https://github.com/rancher/dashboard/pull/6794) - Dashboard team
  - This contains a number of tweaks and fixes to the split out of harvester code from dashboard
  - This will contain a first pass of the dynamic loading of harvester plugin from harvester cluster from 

Harvester Team
- Provide a version of the harvester plugin that will be embedded/bundled with the dashboard
  - This can come in late once we're close to release
- Create an empty `ui-dashboard-harvester-remote-plugin` (name TBD) setting that defaults to empty
  - Provide test environment that will provide a responce to `/v1/harvester/uiinfo`
  - This is already in progress, i'm getting access to fremont
- Complete work to provide the support the endpoint `/v1/harvester/uiinfo`
- There's a lot of code that's moved with the possibility of regressions. In this [PR[(https://github.com/rancher/dashboard/pull/6729) I noted some down in code some areas with `// FIXME: Harvester`. There's also some general areas that we haven't been able to test
  - Upgrade harvester notification/features
  - WebVNC & Serial Console features
  - Navigating between harvester clusters in the multi-cluster environment

There may be a number of items missed, feel free to add or ask any questions

**Comment by WuJun2016** [comment]
> Provide a version of the harvester plugin that will be embedded/bundled with the dashboard
This can come in late once we're close to release

sure,  I think rancher can temporarily use the plugin at this address `https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3-head.tar.gz` while developing.

> Create an empty ui-dashboard-harvester-remote-plugin (name TBD) setting that defaults to empty
I think this ui-dashboard-harvester-remote-plugin should require rancher backend support?

I think this might require the rancher backend to add ui-dashboard-harvester-remote-plugin to the settings, and then we can use it on the frontend.

I think the default value can be set to：  `https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3/harvester-1.0.3.umd.min.js`

> Provide test environment that will provide a responce to /v1/harvester/uiinfo
> This is already in progress, i'm getting access to fremont

The harvester backend pr has been merged, so we don't need to use this `futuretea/harvester:expose-setting-head` image, we use the latest harvester master head image to replace it. ` rancher/harvester:master-head  `

This interface has changed.     `/v1/harvester/uiinfo` => `/v1/harvester/ui-info`
https://github.com/harvester/harvester/pull/2720#discussion_r960477596

> There's a lot of code that's moved with the possibility of regressions. In this [PR[(https://github.com/https://github.com/rancher/dashboard/pull/6729) I noted some down in code some areas with // FIXME: Harvester. There's also some general areas that we haven't been able to test

Okay, I'll test and confirm the area marked `FIXME: Harvester`，    The harvester ui team will conduct a complete round of testing.    


I have a question, when is the rancher team planning to release RC1.

**Comment by richard-cox** [comment]
I've managed to update `./shell/models/harvesterhci.io.management.cluster.js` `loadClusterPlugin` with what we've discussed.
- I forgot about `/ui-info` `ui-source` bundled/remote and have updated the [comment](https://github.com/richard-cox/dashboard/pull/9#issuecomment-1236740256) above
- I still need to fix the embedded use case where `ui-offline-preferred` won't use the bundled package but the `ui-dashboard-harvester-remote-plugin` setting

Regarding a test instance, brilliant. I'll hopefully be able to use fremont. if not i'll redeploy a local harvester to get the merged changes.


> I have a question, when is the rancher team planning to release RC1.

I'm not sure on a Rancher Manager 2.6.9 RC, but the UI should be feature complete by Wednesday 14th. The backend team's is usually about a week earlier

**Comment by WuJun2016** [comment]
I don't think we should use any cache when loading harvester plugin, because each harvester cluster may load a different version of the plugin.

https://github.com/richard-cox/dashboard/blob/test-pluginize-rc-2/shell/models/harvesterhci.io.management.cluster.js#L46

https://github.com/richard-cox/dashboard/blob/test-pluginize-rc-2/shell/models/harvesterhci.io.management.cluster.js#L161

**Comment by richard-cox** [comment]
> https://github.com/richard-cox/dashboard/blob/test-pluginize-rc-2/shell/models/harvesterhci.io.management.cluster.js#L46

The cache of `/ui-info` is per cluster

> https://github.com/richard-cox/dashboard/blob/test-pluginize-rc-2/shell/models/harvesterhci.io.management.cluster.js#L161

The plugins are keyed by `<plugin name>-<version>`. So if a cluster provided a different version it would load the new one... or ignore and use the existing one. This use case is optimised for production builds where there shouldn't be any change in plugin without a change in version. In test/dev world with `-head` builds a refresh would be needed to bring in the new plugin

**Comment by WuJun2016** [comment]
> > https://github.com/richard-cox/dashboard/blob/test-pluginize-rc-2/shell/models/harvesterhci.io.management.cluster.js#L46
> 
> The cache of `/ui-info` is per cluster
> 
> > https://github.com/richard-cox/dashboard/blob/test-pluginize-rc-2/shell/models/harvesterhci.io.management.cluster.js#L161
> 
> The plugins are keyed by `<plugin name>-<version>`. So if a cluster provided a different version it would load the new one... or ignore and use the existing one. This use case is optimised for production builds where there shouldn't be any change in plugin without a change in version. In test/dev world with `-head` builds a refresh would be needed to bring in the new plugin

ok, I see. thanks

**Comment by WuJun2016** [comment]
Hi， @richard-cox   I tested the plugin-related functions and found that the dialog-related functions do not work normal. 

https://github.com/richard-cox/dashboard/blob/test-pluginize-rc-2/shell/utils/dynamic-importer.js#L66

**Comment by richard-cox** [comment]
@WuJun2016 Currently there might be an issue with models (one is fixed [here](https://github.com/rancher/dashboard/pull/6794/commits/316d875f7449578d808123db1ba1b7f055d7d92a)), i need to run through the plugin and fix more. That might effect the custom dialogues if they're opened via model. I'll take a look today

**Comment by richard-cox** [comment]
Superseded by changes in https://github.com/rancher/dashboard/pull/6794

**Pull request closed without merging**
